export const ON_STATISTICS_INITIALIZED = 'ON_STATISTICS_INITIALIZED';
export const ON_STATISTICS_INITIALIZED_SUCCESS = 'ON_STATISTICS_INITIALIZED_SUCCESS';
export const ON_STATISTICS_INITIALIZED_FAIL = 'ON_STATISTICS_INITIALIZED_FAIL';

export const onStatisticsInitialized = () => {
    return {
        type: ON_STATISTICS_INITIALIZED
    }
}
