import {
    ON_TASKS_BOARD_INITIALIZED
} from "store/tasks/actions";

export const deactivated = {
    ON_TASKS_BOARD_INITIALIZED_SUCCESS : ON_TASKS_BOARD_INITIALIZED,
    ON_TASKS_BOARD_INITIALIZED_FAIL : ON_TASKS_BOARD_INITIALIZED,
}

export const activated = {
    ON_TASKS_BOARD_INITIALIZED
}